---
title: "France Economique Report"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
   
---
Row
-----------------------------------------------------------------------
### 
```{r}
#flexdashboard::valueBox(13, caption = " ", icon="fas fa-")
```

```{r}
library(ggplot2)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)

# Charger les données de pays
world <- ne_countries(scale = "medium", returnclass = "sf")

# Filtrer uniquement la Guinée
guinee <- subset(world, name == "Guinea")
# Créer le visuel avec un cadre et une carte
ggplot() +
  geom_sf(data = guinee, fill = "white", color = "black", linewidth = 0.8) +
  theme_minimal(base_size = 14) +
  theme(
    plot.title = element_text(face = "bold", hjust = 0.5, size = 18),
    panel.border = element_rect(color = "white", fill = NA, linewidth = 1),
    panel.background = element_rect(fill = "white")
  )


  

```


### Visuel2
```{r}
flexdashboard::valueBox(2860, caption = "Gross Domestic Product (Billions USD) in 2017", icon="fas fa-euro", color = "#55bd34")

```


### Visuel3
```{r}
flexdashboard::valueBox(37, caption = "Foreign Direct Investment (Billions USD) in 2017", icon="fas fa-circle", color = "#ADD8E6")
```



### Visual4

```{r}
flexdashboard::valueBox(30, caption = "Labor Force (Millions) in 2017", icon="fas fa-person", color = "#41a9b0")
```

Row2
-----------------------------------------------------------------------
### Gross Domestic Product (1990-2017)
```{r}
coube1  <-readr::read_csv("./chapter11data.csv")

```

```{r}
#   produire un graphique linéaire
library(ggplot2)
library(ggthemes)
ggplot(data = coube1, aes(x = year, y = gdp)) +
  geom_line(color = "#55bd34", size = 1) +
  xlab("Years") +
  ylab("Gross domestic product")  +
  theme_minimal() +
  scale_color_brewer(direction = -1)+
  geom_point( color = "#55bd34",size = 2.5)

```


### Foreign Direct Invesment (1990-2017)
```{r}
library(ggplot2)
library(ggthemes)
ggplot(data = coube1, aes(x = year, y = fdi)) +
  geom_line(color = "#ADD8E6",size = 1) +
  xlab("Years") +
  ylab("Foreign Direct Invesment")  +
  theme_minimal() +
  scale_color_brewer(direction = -1)+
  geom_point(color = "#ADD8E6",size = 2.5)

```

### Labor Force (1990-2017)
```{r}
library(ggplot2)
library(ggthemes)
ggplot(data = coube1, aes(x = year, y = laborForce)) +
  geom_line(color = "#41a9b0",size = 1) +
  xlab("Years") +
  ylab("Labor Force")  +
  theme_minimal() +
  scale_color_brewer(direction = -1)+
  geom_point(color = "#41a9b0",size = 2.5)

```

