---
title: "Exo_séance4"
author: "BALDE"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r}
# Etape1_importer les donnees
library(readr)
gdp5 <- read_csv("https://raw.githubusercontent.com/warint/DPR/refs/heads/main/chapter10/data/chapter10data.csv")
```

```{r}
gdp5$country <- as.character(gdp5$country)
```

```{r}
  #   produire un graphique linéaire
library(ggplot2)
library(ggthemes)
ggplot(data = gdp5, aes(x = year, y = gdp, color = country)) +
  geom_line(size = 0.2) +
  xlab("Years") +
  ylab("Gross domestic product")  +
  labs(color = "country")  +  
  theme_minimal() +
  scale_color_brewer(direction = -1)+
  geom_point(size = 0.4)
```
```{r}
# Filter les données pour ne gardé que 2017
library(dplyr)
gdp6 <- filter(gdp5, year==2017)
head(gdp6)
```

```{r}
# créer un graphique à barre
library(ggplot2)
library(ggthemes)
ggplot(data = gdp5, aes(x = country, y =gdp , fill = country)) + 
  geom_bar(stat = "identity", width = 0.8, position = "dodge") +
  xlab("") +
  ylab("Gross domestic product")  +
  labs(fill = "Country")  +  
  theme_minimal() + 
  scale_fill_brewer(direction = 1)
```

